### ISSUE TITLE
"Audio Unit Extension quit" in Garageband iOS - Digital D1

### ISSUE THREAD

**Issue by jonathanhirz** [AudioKit/AudioKitSynthOne#113]
Hello! First off, sorry if this is in the wrong spot. I don't see a repo for Digital D1, but I figure things are related here. I am seeing a pretty consistent crash in Garageband for iOS when using Digital D1 as an Audio Unit Extension. It might be related to using an Arp preset, or something with AUv3 in general. I'll give steps below to get to the crash. I'm using a 2018 iPad 9.7" on iOS 13.1.2, so maybe it's just a memory issue or something with iOS 13.

Steps:
Close all applications
Open Garageband
New project, add external instrument, Audio Unit Extension
Select Digital D1
Choose preset "7-50: Insistence Arp" (for example, I just keep choosing the same one since I know it crashes, but I think it happens with others)
Play some notes and wait for crash.

Any ideas why this is happening? Thanks for any input, I love this project!

**Comment by aure** [comment]
I believe Xcode 11 or iOS13/iPadOS introduced a bug that I have fixed in the latest AudioKit 4.9.1. We will compile with the new version of AudioKit and release a new version asap. Please check again after this update and let us know if you still have issues. We're always working to improve and sometimes we get it wrong, sometimes we have to react quickly to an Apple change. This time might have been a combination of both.
