### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by bmeverett** [AudioKit/AudioKitSynthOne#5]
Looks like the most recent commit of adding in ABLink is failing. It's currently included in the `AudioKitSynthOne-Bridging-Header.h` but doesn't look to be included in the project. This is resulting in build errors.

It looks like the files have been added to the `.gitignore` so they weren't checked into the project. https://github.com/AudioKit/AudioKitSynthOne/blob/master/.gitignore#L70-L71

You should also look into updating the TravisCI build to fail if the project doesn't build. Looks like xcbuild always returns an exit code of 0 no matter if the project fails to build or not.  Here's a quick stack overflow answer on a simple remedy!  https://stackoverflow.com/questions/7363459/how-to-get-the-return-value-of-xcodebuild

Thanks again for this project and let me know of anything I can do to help get this resolved!

**Comment by aure** [comment]
Interesting, I thought I got it so that develop still built (it did on my machine) without Link in place.  Honestly, the best bet for you going forward is to get Link and get those files.  At this point, Ableton isn't allowing us to distribute the files outside of their own private repo.  As far as Travis, can you you @megastep have a look?

**Comment by megastep** [comment]
Haven't looked at this yet but I assume we'll have to turn it off by default for Travis and other builds to complete if the files are not here.

**Comment by bmeverett** [comment]
@aure good to know. Maybe you can put some info in the README linking to Ableton link? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by megastep** [comment]
@bmeverett Thanks! I've fixed the Travis config so we do catch build failures, and added a custom user setting in the project so that we can turn on Ableton Link explicitly. It is disabled by default so the user can turn it on when they have the SDK files.

I've also added a blurb in the README about this, though @aure might want to elaborate on that.
